# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockit < Formula
  desc "The CLI tool provides a convenient way to set up access to remote Docker servers hosted by Dockit."
  homepage "https://github.com/dockit-dev/dockit"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dockit-dev/dockit/releases/download/v0.1.0/dockit_0.1.0_Darwin_arm64.tar.gz"
      sha256 "5642e50c588179e2b214849091734927d8f8f4c40845ed7506b916c2c5d3f2d5"

      def install
        bin.install "dockit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dockit-dev/dockit/releases/download/v0.1.0/dockit_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "0fb6fa4d001c71bee466933013f593700d40a8ef1f7e0ac456887a2d77f5ddbf"

      def install
        bin.install "dockit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dockit-dev/dockit/releases/download/v0.1.0/dockit_0.1.0_Linux_arm64.tar.gz"
      sha256 "782c2771b1624473a6ccd98f75d6053234af8c6a96d936371a0c2964faa17649"

      def install
        bin.install "dockit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dockit-dev/dockit/releases/download/v0.1.0/dockit_0.1.0_Linux_x86_64.tar.gz"
      sha256 "beb432fb00db4abd06c5b2ef16cfc50fcc45b5f7756fa29ed48055850e49ff8a"

      def install
        bin.install "dockit"
      end
    end
  end
end
